from pathlib import Path
from eth_hash.auto import keccak
from random import randbytes, randint, seed, sample
from more_itertools import sliced

# need
# python -m pip install "eth-hash[pycryptodome]"

seed(1337)

SIZE = 100
MALLOC_COST_PER_BYTE = 10

OLD_BASE = 50
OLD_PER_ARG = 160
OLD_PER_BYTE = 2

NEW_BASE = 2350
NEW_PER_ARG = 100
NEW_PER_BYTE = 10

def generate(path, base, per_arg, per_byte):
    with open(path, "w+") as f:
        f.write("; This file was generated by tools/generate-keccak-tests.py\n\n")

        for i in range(SIZE):
            blob = randbytes(randint(1, 30))
            result = keccak(blob)

            for i in range(1, len(blob) + 1):
                args = sliced(blob, i)
                num_args = (len(blob) + i - 1) // i
                cost = base + len(blob) * per_byte + num_args * per_arg + len(result) * MALLOC_COST_PER_BYTE
                args_str = " ".join([f"0x{a.hex()}" for a in args])
                f.write(f"keccak256 {args_str} => 0x{result.hex()} | {cost}\n")

    print(f"Generated: {path}")

base = Path(__file__).parent.parent / "op-tests"
generate(base / "test-keccak256-generated.txt", OLD_BASE, OLD_PER_ARG, OLD_PER_BYTE)
generate(base / "test-keccak256-generated-v2.txt", NEW_BASE, NEW_PER_ARG, NEW_PER_BYTE)
