from eth_hash.auto import keccak
from random import randbytes, randint, seed, sample
from more_itertools import sliced

# need
# python -m pip install "eth-hash[pycryptodome]"

seed(1337)

SIZE = 100

with open("../op-tests/test-keccak256-generated.txt", "w+") as f:
    f.write("; This file was generated by tools/generate-keccak-tests.py\n\n")

    for i in range(SIZE):

        blob = randbytes(randint(1, 30))
        result = keccak(blob)

        for i in range(1, len(blob) + 1):
            args = sliced(blob, i)
            cost = 50 + len(blob) * 2 + (len(blob)+i-1)//i * 160 + len(result) * 10
            args_str = " ".join([f"0x{a.hex()}" for a in args])
            f.write(f"keccak256 {args_str} => 0x{result.hex()} | {cost}\n")
