name: Build ARM64 wheels

on:
  push:
    branches:
      - main
      - dev
      - arm64
    tags:
        - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build_wheels:
    name: ARM64 Wheel on py-${{ matrix.python }}
    runs-on: ARM64
    strategy:
      matrix:
        python: [37, 38, 39]
#        os: [ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Build and test wheels
      run: |
        podman run --rm=true \
          quay.io/pypa/manylinux2014_aarch64 \
          bash -exc '\
            curl https://sh.rustup.rs -sSf | sh && \
            /opt/python/${{ matrix.python }}-${{ matrix.python }}/python \
              -m venv venv && \
              ln -s venv/bin/activate && \
              . ./activate && \
            pip install maturin && \
            maturin build -i python --release --manylinux 2014 \
          '

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: clvm_rs/target/wheels/

    - name: Install Twine
      run: pip install twine

    - name: Test for secrets access
      id: check_secrets
      shell: bash
      run: |
        unset HAS_SECRET
        if [ -n "$SECRET" ]; then HAS_SECRET='true' ; fi
        echo ::set-output name=HAS_SECRET::${HAS_SECRET}
      env:
        SECRET: "${{ secrets.test_pypi_password }}"

    - name: publish (PyPi)
      if: startsWith(github.event.ref, 'refs/tags') && steps.check_secrets.outputs.HAS_SECRET
      env:
        TWINE_USERNAME: __token__
        TWINE_NON_INTERACTIVE: 1
        TWINE_PASSWORD: ${{ secrets.pypi_password }}
      run: twine upload --non-interactive --skip-existing --verbose 'clvm_rs/target/wheels/*'

    - name: publish (Test PyPi)
      if: steps.check_secrets.outputs.HAS_SECRET
      env:
        TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
        TWINE_USERNAME: __token__
        TWINE_NON_INTERACTIVE: 1
        TWINE_PASSWORD: ${{ secrets.test_pypi_password }}
      run: twine upload --non-interactive --skip-existing --verbose 'clvm_rs/target/wheels/*'
