name: Build ARM64 wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: ARM64 Wheel on py-${{ matrix.python }}
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_aarch64
    strategy:
      fail-fast: false
      matrix:
        python: [37, 38, 39]
#        os: [ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up rust
      run: |
        curl https://sh.rustup.rs -sSf | sh

    - name: Build Linux ARM64 with maturin on Python ${{ matrix.python }}
      run: |
        /opt/python/cp${{ matrix.python }}-${{ matrix.python }}mu/python -m venv venv
        ln -s venv/bin/activate
        . ./activate
        pip install maturin
        maturin build -i python --release --manylinux 2014

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: ./target/wheels/

    - name: Install Twine
      run: pip install twine

    - name: Test for secrets access
      id: check_secrets
      shell: bash
      run: |
        unset HAS_SECRET
        if [ -n "$SECRET" ]; then HAS_SECRET='true' ; fi
        echo ::set-output name=HAS_SECRET::${HAS_SECRET}
      env:
        SECRET: "${{ secrets.test_pypi_password }}"

    - name: publish (PyPi)
      if: startsWith(github.event.ref, 'refs/tags') && steps.check_secrets.outputs.HAS_SECRET
      env:
        TWINE_USERNAME: __token__
        TWINE_NON_INTERACTIVE: 1
        TWINE_PASSWORD: ${{ secrets.pypi_password }}
      run: twine upload --non-interactive --skip-existing --verbose 'target/wheels/*'

    - name: publish (Test PyPi)
      if: steps.check_secrets.outputs.HAS_SECRET
      env:
        TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
        TWINE_USERNAME: __token__
        TWINE_NON_INTERACTIVE: 1
        TWINE_PASSWORD: ${{ secrets.test_pypi_password }}
      run: twine upload --non-interactive --skip-existing --verbose 'target/wheels/*'
